# Site settings
title: Tech Trends and Careers
author: Max Bernstein
author_nickname: Max
email: exp57@bernsteinbear.com
description: "An ExCollege class about navigating life after college"
baseurl: "/excollege"
url: "https://bernsteinbear.com/excollege/"

# Build settings
markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown
  hard_wrap: false
highlighter: rouge
